# Generated by Django 4.1.1 on 2022-10-07 15:51

import Vehiculos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('año', models.IntegerField()),
                ('precio', models.FloatField()),
                ('usado', models.BooleanField(default=False)),
                ('imagen', models.ImageField(null=True, upload_to=Vehiculos.models.dirImagen)),
                ('vendido', models.BooleanField(default=False)),
                ('vendidoA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Vehiculos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehiculos.cliente')),
                ('vehiculo_comprado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehiculos.vehiculos')),
            ],
        ),
        migrations.CreateModel(
            name='categoria_vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.IntegerField(choices=[(1, 'ligeros'), (2, 'pesados'), (3, 'especiales'), (4, 'agricolas'), (5, 'otros')])),
                ('vehiculos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehiculos.vehiculos')),
            ],
        ),
    ]
